site_name: '&nbsp;'
site_url: https://toolkit.tpau.group/
repo_url: https://github.com/T-Pau/Toolkit
copyright: Â©2025 Dieter Baron
extra:
  generator: false
extra_css:
  - assets/styles/mkdocstrings.css
plugins:
  - extra-sass
  - privacy
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ['Toolkit/python-packages']
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: spacy
            merge_init_into_class: true
            show_docstring_attributes: true
            show_docstring_functions: true
            show_docstring_classes: true
            show_source: false
            show_symbol_type_heading: true
            show_attribute_values: false
theme:
  name: material
  custom_dir: overrides
  font: false
  # logo: assets/images/logo.svg
  logo: assets/images/tpau.svg
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github   
  palette:
    primary: custom
  features:
    - navigation.indexes 
    - toc.integrate 
markdown_extensions:
  def_list: {}
nav:
  - index.md
  - Tutorials:
    - Tutorials/index.md
  - How-To Guides:
    - How-To-Guides/index.md
  - Reference: 
    - Reference/index.md
    - Scripts:
      - Reference/Scripts/index.md
      - Reference/Scripts/convert-bitmaps.md
      - Reference/Scripts/convert-characters.md
      - Reference/Scripts/convert-charset.md
      - Reference/Scripts/convert-image.md
      - Reference/Scripts/convert-markdown.md
      - Reference/Scripts/convert-screens.md
      - Reference/Scripts/convert-sprites.md
      - Reference/Scripts/create-disk.md
      - Reference/Scripts/create-zip.md
      - Reference/Scripts/encode-colors.md
      - Reference/Scripts/parallel-struct.md
    - Python Classes:
      - Reference/Classes/index.md
      - Reference/Classes/AssemblerOutput.md
      - Reference/Classes/AtomicOutput.md
      - Reference/Classes/Buffer.md
      - Reference/Classes/CharacterMapping.md
      - Reference/Classes/Charset.md
      - Reference/Classes/Command.md
      - Reference/Classes/Dependencies.md
      - Reference/Classes/FileReader.md
      - Reference/Classes/Palette.md
      - Reference/Classes/PaletteImage.md
      - Reference/Classes/Script.md
      - Reference/Classes/YAMLSpec.md
  - Explanations:
    - Explanations/index.md
  - License.md
  - Repository: 'https://github.com/T-Pau/Toolkit/'
